### PR TITLE
fix: enforce imdsv2 for cloudconnector instances

### PR DESCRIPTION
**Pull request by anichari**

### CODE REVIEW

**Comment by anichari** [comment]
@apandit13 can you please help verify the imdsv2 enforcement fix on this branch

**Review by smone77 — APPROVED** [review]
LGTM

**Comment by anichari** [comment]
> LGTM

Thanks will leave this PR open until testing complete and the relevant ami is pushed to Marketplace

**Comment by anichari** [comment]
@apandit13 and Tony George have verified the fix. merging

**Pull request merged**
