### PR TITLE
fix: asg - move cc instance size to ec2 instance type validation from…

### PR DESCRIPTION
**Pull request by anichari**
The validation for cc instance size to ec2 instance type has been moved from the pre-deployment macro to the asg template as a Rule.

### CODE REVIEW

**Comment by anichari** [comment]
@apandit13 please let us know once you have validated the fix

**Comment by anichari** [comment]
@smone77 , @jmolnar-zscaler please review and +1 for the P0 by today if possible

**Review by jmolnar-zscaler — DISMISSED** [review]
Lgtm

**Review by smone77 — APPROVED** [review]
LGTM

**Comment by anichari** [comment]
Closing this in lieu of branching from main

**Pull request closed without merging**
